# Generated by Django 5.1.4 on 2025-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_paymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='installment_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
